version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /usr/src/app/
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=spartagora_back_db
      - POSTGRES_USER=spartagora_back_3team
      - POSTGRES_PASSWORD=spartagora_back_password

volumes:
  postgres_db:
